export const ROUTES = {
  DASHBOARD: '/',
  SHOPS: '/shops',
  ADMIN_MY_SHOPS: '/my-shops',
  CREATE_SHOP: '/shops/create',
  LOGIN: '/login',
  ORDER_STATUS: '/order-status',
  ORDERS: '/orders',
  USER_ORDERS: '/orders/createFromUserEnd',
  BUYERS: '/buyers',
  PRICE_SCHEDULES: '/price-schedules',
  CREATE_ORDER: '/orders/create',
  PRODUCTS: '/products',
  COUPONS: '/coupons',
  CUSTOMERS: '/customers',
  VERIFY_COUPONS: '/coupons/verify',
  USERS: '/users',
  PROMOTIONS: '/promotions',
  TAXES: '/taxes',
  SHIPPINGS: '/shippings',
  SETTINGS: '/settings',
  STORE_SETTINGS: '/vendor/settings',
  STORE_KEEPER: '/vendor/store_keepers',
  CATEGORIES: '/categories',
  ATTRIBUTES: '/attributes',
  ATTRIBUTE_VALUES: '/attribute-values',
  GROUPS: '/groups',
  TAGS: '/tags',
  WITHDRAWS: '/withdraws',
  PROFILE_UPDATE: '/profile-update',
  LOGOUT: '/logout',
  STAFFS: '/staffs',
  REFUNDS: '/refunds',
  AUTHORS: '/authors',
  MANUFACTURERS: '/manufacturers',
  CHECKOUT: '/orders/checkout',
  ORGANIZATION:'/organization',
  QUOTES:'/quotes',
  USERGROUPS:'/user-groups',
  CREATE_USERGROUPS:'/user-groups/create',
  CART: '/cart'
};
